Documentation:
  Enabled: false

AllCops:
  Excludes:
    - 'bin/bundle'
    - 'bin/ci'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 12
