version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: app
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
        - "3307:3306"
    env_file: .env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/uploadcare-rails-example
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env

volumes:
  bundle:
